version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - ./node_modules/.bin/gulp lint
      - ./node_modules/.bin/gulp test